# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='name',
            field=models.CharField(default='old strat', max_length=100),
        ),
    ]
