# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 13:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strategies', '0002_strategy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
