# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0004_auto_20170510_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='steps',
            name='image',
            field=stdimage.models.StdImageField(upload_to=stdimage.utils.UploadToUUID(path='images'), verbose_name=stdimage.utils.UploadToClassNameDir()),
        ),
    ]
